export const DAY_IN_SECONDS   = 86400;
export const MONTH_IN_SECONDS = DAY_IN_SECONDS * 30;
export const YEAR_IN_SECONDS  = MONTH_IN_SECONDS * 12;

export const DAY_IN_MILLISECONDS   = DAY_IN_SECONDS * 1000;
export const MONTH_IN_MILLISECONDS = MONTH_IN_SECONDS * 1000;
export const YEAR_IN_MILLISECONDS  = YEAR_IN_SECONDS * 1000;