# This is a basic workflow to help you get started with Actions

name: PSI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Measuring the root page
      uses: jakepartusch/psi-action@v1.2
      id: root
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/"
        strategy: desktop
        
    - name: Measuring the terms page
      uses: jakepartusch/psi-action@v1.2
      id: terms
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/"
        strategy: desktop
