# This is a basic workflow to help you get started with Actions

name: PSI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Measuring the root page
      uses: jakepartusch/psi-action@v1.2
      id: root
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
        
    - name: Measuring the terms page
      uses: jakepartusch/psi-action@v1.2
      id: terms
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/terms"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
        
    - name: Measuring the post page
      uses: jakepartusch/psi-action@v1.2
      id: post
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/posts/01EXH20KRBVP34RYHYDTSX8JS2"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
        
    - name: Measuring the profile page
      uses: jakepartusch/psi-action@v1.2
      id: profile
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/users/mexicandraggle"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
    
    - name: Measuring the post page 2
      uses: jakepartusch/psi-action@v1.2
      id: post2
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/posts/01EXH20KRBVP34RYHYDTSX8JS2"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
        
    - name: Measuring the post page 3
      uses: jakepartusch/psi-action@v1.2
      id: post3
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/posts/01EXNV3BSJV18WFYBS87TP4NFC"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
        
    - name: Measuring the post page 4
      uses: jakepartusch/psi-action@v1.2
      id: post4
      with:
        url: "https://web-speed-hackathon-335112.an.r.appspot.com/posts/01EX0SGMRHZP5JBA5JF2ZZQTP2"
        strategy: desktop
        key: ${{ secrets.PSI_APIKEY }}
